---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MTIxMw==
  USER_DB: cG9zdGdyZXM=
  PASS_DB: MTIxMw==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-map
  labels:
    app: postgresdb-config-map
data:
  HOST_DB: pg-service
  PORT_DB: "5432"
  DB_NAME: UserDb
  ASPNETCORESTAGE: Realase

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: postgres
          envFrom:
            - secretRef:
                name: pg-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  selector:
    app: postgresdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
        - name: app-api
          image: 1t234tyio/otusminiapi
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8081
          envFrom:
            - secretRef:
                name: pg-secrets
            - configMapRef:
                name: app-config-map

---
apiVersion: v1
kind: Service
metadata:
  name: app-api-service
spec:
  selector:
    app: app-api
  ports:
    - name: htpp-port
      protocol: TCP
      port: 80
      targetPort: http
    - name: htpps-port
      protocol: TCP
      port: 443
      targetPort: https

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ef-migration
spec:
  template:
    spec:
      containers:
        - name: migration-container
          image: 1t234tyio/otusminiapi
          command:
            [
              "dotnet",
              "ef",
              "database",
              "update",
              "--project",
              "../src/OtusMiniApi",
            ]
          envFrom:
            - secretRef:
                name: pg-secrets
            - configMapRef:
                name: app-config-map

      restartPolicy: OnFailure
  backoffLimit: 5
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-api-service
                port:
                  number: 80
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-api-service
                port:
                  number: 443
