{
 "title": "quantile 50%",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "Latency of service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (sum by(le) (histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{service=\"metrics-mini-api\"}[$__rate_interval]))))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod) (sum by(le) (histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{service=\"metrics-mini-api\"}[$__rate_interval]))))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod) (sum by(le) (histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{service=\"metrics-mini-api\"}[$__rate_interval]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS of SERVICE",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(microsoft_aspnetcore_hosting_requests_per_second_total{service=\"metrics-mini-api\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate ingress server",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod) (microsoft_aspnetcore_hosting_http_server_request_duration_bucket{http_response_status_code=\"500\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint, method) (rate(http_requests_received_total{service=\"metrics-mini-api\", method=\"GET\", endpoint=\"api/Users\"}[$__interval]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum by(endpoint, method) (rate(http_requests_received_total{service=\"metrics-mini-api\", method=\"POST\", endpoint=\"api/Users\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(endpoint, method) (rate(http_requests_received_total{service=\"metrics-mini-api\", method=\"PUT\", endpoint=\"api/Users\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "quantile ",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{service=\"metrics-mini-api\", endpoint=\"api/Users\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(le) (histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{service=\"metrics-mini-api\", endpoint=\"api/Users\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(le) (histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{service=\"metrics-mini-api\", endpoint=\"api/Users\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 24 },
   "targets": [
    {
     "expr": "sum by(http_request_method) (microsoft_aspnetcore_hosting_http_server_request_duration_count{http_response_status_code=\"500\", service=\"metrics-mini-api\", http_request_method=\"GET\", http_route=\"api/Users\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(http_request_method) (microsoft_aspnetcore_hosting_http_server_request_duration_count{http_response_status_code=\"500\", service=\"metrics-mini-api\", http_request_method=\"POST\", http_route=\"api/Users\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(http_request_method) (microsoft_aspnetcore_hosting_http_server_request_duration_count{http_response_status_code=\"500\", service=\"metrics-mini-api\", http_request_method=\"PUT\", http_route=\"api/Users\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}