apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-map
  labels:
    app: postgresdb-config-map
data:
  HOST_DB: {{.Values.configMap.HOSTDB}} 
  DB_NAME: {{.Values.configMap.DBNAME}}
  ASPNETCORESTAGE: {{.Values.configMap.ASPNETCORESTAGE}}