apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvlocal
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" 
  hostPath:
    path: /app/keyFile
