apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  selector:
    app: {{ .Values.deploymentdb.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.deploymentdb.port }}
      targetPort: {{ .Values.deploymentdb.port }}
