# Default values for demoapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 2
backoffLimit: 5

portAppHttp: 8080
portAppHttps: 8081

configMap:
  HOSTDB: pg-service
  
  DBNAME: UserDb
  ASPNETCORESTAGE: Realase
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: 1t234tyio/otusminiapi
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  portNameHttp: http
  portNameHttps: https
  # Overrides the image tag whose default is the chart appVersion.

# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  className: nginx
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: arch.homework
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

deploymentdb:
  port: 5432
  image: postgres
  replicaCount: 1
  label: postgresdb

  containername: postgresdb

apygetway:
  host: http://app-api-service

serviceApp:
  portNameHttp: htpp-port
  portHttp: 80
  portNameHttps: htpps-port
  portHttps: 443
